src/Entity/Property.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PropertyRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{
    const MANAGE = [
        "" => '',
        0 => 'Oui',
        1 => 'Non',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 5,
        max: 255,
        minMessage: 'Votre titre est trop court. Il doit contenir au minimum 5 caractères',
        maxMessage: 'Votre titre est trop long. Il doit contenir au maximum 255 caractères',
    )]
    private ?string $Title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\Range(
        min: 10,
        max: 400,
        notInRangeMessage: 'Cette valeur doit être comprise entre 10cm² et 400cm²',
    )]
    private ?float $Surface = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\Range(
        min: 2,
        notInRangeMessage: 'Cette valeur doit être au moins égale à 2',
    )]
    private ?int $Rooms = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?int $Bedrooms = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull()]
    #[Assert\Length(
        min: 5,
        max: 255,
        minMessage: 'La valeur de ce champ est trop court. Il doit contenir au minimum 5 caractères',
        maxMessage: 'La valeur de ce champ est trop long. Il doit contenir au maximum 255 caractères',
    )]
    private ?string $Address = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(
        max: 255,
        maxMessage: 'La valeur de ce champ est trop long. Il doit contenir au maximum 255 caractères',
    )]
    private ?string $Additional_address = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull()]
    #[Assert\Length(
        min: 5,
        max: 255,
        minMessage: 'La valeur de ce champ est trop court. Il doit contenir au minimum 5 caractères',
        maxMessage: 'La valeur de ce champ est trop long. Il doit contenir au maximum  255 caractères',
    )]
    private ?string $City = null;

    #[ORM\Column]
    #[Assert\Regex('/^[0-9]{5}$/')]
    private ?string $Postal_code = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\Positive()]
    private ?float $Price_charges = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\Positive()]
    private ?float $Rent_price = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\Positive()]
    private ?float $Security_deposit_price = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $CreatedAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $UpdatedAt = null;


    #[ORM\ManyToOne(inversedBy: 'property')]
    private ?Tenant $tenant = null;



    #[ORM\Column(nullable: true)]
    private ?float $totalPrice = null;

    #[ORM\Column(nullable: true)]
    private ?float $DepositLoyer = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $manageByAgency = null;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->CreatedAt = new DateTimeImmutable();
        $this->UpdatedAt = new \DateTimeImmutable();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->Surface;
    }

    public function setSurface(float $Surface): self
    {
        $this->Surface = $Surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->Rooms;
    }

    public function setRooms(int $Rooms): self
    {
        $this->Rooms = $Rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->Bedrooms;
    }

    public function setBedrooms(int $Bedrooms): self
    {
        $this->Bedrooms = $Bedrooms;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getAdditionalAddress(): ?string
    {
        return $this->Additional_address;
    }

    public function setAdditionalAddress(?string $Additional_address): self
    {
        $this->Additional_address = $Additional_address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->Postal_code;
    }

    public function setPostalCode(string $Postal_code): self
    {
        $this->Postal_code = $Postal_code;

        return $this;
    }

    public function getPriceCharges(): ?float
    {
        return $this->Price_charges;
    }

    public function setPriceCharges(float $Price_charges): self
    {
        $this->Price_charges = $Price_charges;

        return $this;
    }

    public function getRentPrice(): ?float
    {
        return $this->Rent_price;
    }

    public function setRentPrice(float $Rent_price): self
    {
        $this->Rent_price = $Rent_price;

        return $this;
    }

    public function getSecurityDepositPrice(): ?float
    {
        return $this->Security_deposit_price;
    }

    public function setSecurityDepositPrice(float $Security_deposit_price): self
    {
        $this->Security_deposit_price = $Security_deposit_price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function getTenant(): ?Tenant
    {
        return $this->tenant;
    }

    public function setTenant(?Tenant $tenant): self
    {
        $this->tenant = $tenant;

        return $this;
    }


    public function getTotalPrice(): ?float
    {
        return $this->totalPrice;
    }

    public function setTotalPrice(?float $totalPrice): self
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }

    #[ORM\PrePersist()]
    #[ORM\PreUpdate()]
    public function updateTotalPrice()
    {
        $this->totalPrice = $this->Price_charges + $this->Rent_price;
    }

    public function getDepositLoyer(): ?float
    {
        return $this->DepositLoyer;
    }

    public function setDepositLoyer(?float $DepositLoyer): self
    {
        $this->DepositLoyer = $DepositLoyer;

        return $this;
    }


    public function __toString()
    {
        return $this->getTitle();
    }

    public function getManageByAgency(): ?string
    {
        return $this->manageByAgency;
    }

    public function setManageByAgency(?string $manageByAgency): self
    {
        $this->manageByAgency = $manageByAgency;

        return $this;
    }

    public function getManageType(): ?string
    {
        return self::MANAGE[$this->manageByAgency];
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Form\PropertyType;
use App\Form\EditPropertyType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{
    #[Route('/property', name: 'app_property',  methods: ['GET'])]
    public function index(PropertyRepository $repository, PaginatorInterface $paginator, Request $request): Response
    {
        $propertys = $paginator->paginate(
            $repository->findAll(),
            $request->query->getInt('page', 1), /*page number*/
            10
        );

        return $this->render('property/property.html.twig', [
            'propertys' => $propertys
        ]);
    }

    #[Route('/property/new', name: 'app_property_new',  methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $property = $form->getData();

            $manager->persist($property);
            $manager->flush();

            $this->addFlash(
                'success',
                'La propriétée à été ajoutée avec succès !'
            );
            return $this->redirectToRoute('app_property');
        }

        return $this->render('property/newProperty.html.twig', [
            'form' => $form->createView()
        ]);
    }


    #[Route('/property/edit/{id}', 'app_property_edit',  methods: ['GET', 'POST'])]
    public function edit(Property $property, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(PropertyType::class, $property);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $property = $form->getData();
            if ($form['tenant']->getData()) {

                $manager->persist($property);
                $manager->flush();

                $this->addFlash(
                    'success',
                    'La propriétée à été ajoutée avec succès !'
                );

                return $this->redirectToRoute('app_etat_des_lieux_new');
            } elseif (empty($form['tenant']->getData())) {

                $manager->persist($property);
                $manager->flush();

                $this->addFlash(
                    'success',
                    'La propriétée à été ajoutée avec succès !'
                );

                return $this->redirectToRoute('app_property');
            }
        }

        return $this->render('property/editProperty.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/property/delete/{id}', 'app_property_delete',  methods: ['GET'])]
    public function delete(EntityManagerInterface $manager, Property $property): Response
    {
        $manager->remove($property);
        $manager->flush();


        $this->addFlash(
            'success',
            'La propriétée à été supprimé avec succès !'
        );

        return $this->redirectToRoute('app_property');
    }
}

templates/property/editProperty.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Editer une propriétée
{% endblock %}

{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-success">
		<div class="container-fluid">
			<a class="navbar-brand" href="#">AgenceImmobillièreFictive</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor03">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link active" href="#">Utilisateurs
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_property') }}">Propriétées
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_tenant') }}">Locataires
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_payment') }}">Paiements
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<h1 class="mt-5">
			Modifier une propriétée
		</h1>

		{{ form_start(form) }}
		<div class="row mt-5">
			<div class="col-md-4">{{ form_row(form.Title)}}</div>
			<div class="col-md-8">{{ form_row(form.Description)}}</div>
		</div>

		<div class="row">
			<div class="col-md-4">{{ form_row(form.Surface)}}</div>
			<div class="col-md-4">{{ form_row(form.Rooms)}}</div>
			<div class="col-md-4">{{ form_row(form.Bedrooms)}}</div>
		</div>

		<div class="row">
			<div class="col-md-4">{{ form_row(form.Price_charges)}}</div>
			<div class="col-md-4">{{ form_row(form.Rent_price)}}</div>
			<div class="col-md-4">{{ form_row(form.Security_deposit_price)}}</div>
		</div>

		<div class="row">
			<div class="col-md-6">{{ form_row(form.Address)}}</div>
			<div class="col-md-6">{{ form_row(form.Additional_address)}}</div>
		</div>

		<div class="row">
			<div class="col-md-6">{{ form_row(form.City)}}</div>
			<div class="col-md-6">{{ form_row(form.Postal_code)}}</div>
		</div>
		{{ form_end(form) }}
	</div>

{% endblock %}

templates/property/newProperty.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Ajouter une propriétée
{% endblock %}

{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-success">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ path('app_home') }}">AgenceImmobillièreFictive</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor03">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_property') }}">Propriétées
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_tenant') }}">Locataires
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_payment') }}">Paiements
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_etat_des_lieux') }}">Etat des lieux
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_login_logout') }}">Se déconnecter
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<h1 class="mt-5">
			Ajouter une propriété
		</h1>

		{{ form_start(form) }}
		<div class="row">
			<div class="col-md-4">{{ form_row(form.Title)}}</div>
			<div class="col-md-8">{{ form_row(form.Description)}}</div>
		</div>

		<div class="row">
			<div class="col-md-4">{{ form_row(form.Surface)}}</div>
			<div class="col-md-4">{{ form_row(form.Rooms)}}</div>
			<div class="col-md-4">{{ form_row(form.Bedrooms)}}</div>
		</div>

		<div class="row">
			<div class="col-md-4">{{ form_row(form.Price_charges)}}</div>
			<div class="col-md-4">{{ form_row(form.Rent_price)}}</div>
			<div class="col-md-4">{{ form_row(form.Security_deposit_price)}}</div>
		</div>

		<div class="row">
			<div class="col-md-6">{{ form_row(form.Address)}}</div>
			<div class="col-md-6">{{ form_row(form.Additional_address)}}</div>
		</div>

		<div class="row">
			<div class="col-md-6">{{ form_row(form.City)}}</div>
			<div class="col-md-6">{{ form_row(form.Postal_code)}}</div>
		</div>

		<div class="row">
			<div class="col-md-12">{{ form_row(form.manage_by_agency)}}</div>

		</div>
		{{ form_end(form) }}
	</div>

{% endblock %}

templates/property/property.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Propriétées
{% endblock %}

{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-success">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ path('app_home') }}">AgenceImmobillièreFictive</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor03">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_property') }}">Propriétées
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_tenant') }}">Locataires
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_payment') }}">Paiements
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_etat_des_lieux') }}">Etat des lieux
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_login_logout') }}">Se déconnecter
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div style="padding: 75px;" class="mt-4">
		<div class="jumbotron">
			<h1 class="mb-5">
				Liste des propriétées
			</h1>

			{% for message in app.flashes('success') %}
				<div class="alert alert-success mt-4">
					{{ message }}
				</div>
			{% endfor %}

			<table class="table table-hover">
				<thead>
					<tr>
						<th scope="col">Numéros</th>
						<th scope="col">Titre</th>
						<th scope="col">Description</th>
						<th scope="col">Surface</th>
						<th scope="col">Pièces</th>
						<th scope="col">Chambre</th>
						<th scope="col">Adresse</th>
						<th scope="col">Complément d'adresse</th>
						<th scope="col">Ville</th>
						<th scope="col">Code postal</th>
						<th scope="col">Prix des charges</th>
						<th scope="col">Prix du loyer</th>
						<th scope="col">Prix du dépot de garantie</th>
						<th scope="col">Gérer par l'agence</th>
						<th scope="col">Locataire</th>
						<th scope="col"></th>
						<th scope="col"></th>
					</tr>
				</thead>

				<tbody>
					{% for property in propertys|sort %}
						<tr class="table-light">
							<th scope="row">{{ property.id }}</th>
							<td>{{ property.title }}</td>
							<td>{{ property.description }}</td>
							<td>{{ property.surface }}</td>
							<td>{{ property.rooms }}</td>
							<td>{{ property.bedrooms }}</td>
							<td>{{ property.address }}</td>
							<td>{{ property.additionaladdress }}</td>
							<td>{{ property.city }}</td>
							<td>{{ property.postalcode }}</td>
							<td>{{ property.pricecharges }}</td>
							<td>{{ property.rentprice }}</td>
							<td>{{ property.securitydepositprice }}</td>
							<td>{{ property.ManageType}}</td>
							<td>{{ property.tenant }}</td>
							
							<td>
								<a href="{{ path('app_property_edit', {id: property.id}) }}" class="btn btn-warning">
									Editer
								</a>
							</td>
							<td>
								<a href="{{ path('app_property_delete', {id: property.id}) }}" class="btn btn-danger">
									Supprimer
								</a>
							</td>

						</tr>
					{% endfor %}
				</tbody>
			</table>

			<div class="navigation d-flex justify-content-center">
				{{ knp_pagination_render(propertys) }}
			</div>

			<a href="{{ path('app_property_new') }}" class="btn btn-success mt-4 d-flex justify-content-center">
				Ajouter une propriétée
			</a>

		</div>
	</div>
{% endblock %}