src/Entity/Payments.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PaymentsRepository;

#[ORM\Entity(repositoryClass: PaymentsRepository::class)]
class Payments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'payment')]
    private ?Tenant $Tenant = null;

    #[ORM\Column(length: 255)]
    private ?string $Invoice = null;

    #[ORM\Column(length: 255)]
    private ?string $Amount = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Property = null;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTenant(): ?Tenant
    {
        return $this->Tenant;
    }

    public function setTenant(?Tenant $Tenant): self
    {
        $this->Tenant = $Tenant;

        return $this;
    }

    public function getInvoice(): ?string
    {
        return $this->Invoice;
    }

    public function setInvoice(string $Invoice): self
    {
        $this->Invoice = $Invoice;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->Amount;
    }

    public function setAmount(string $Amount): self
    {
        $this->Amount = $Amount;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getProperty(): ?string
    {
        return $this->Property;
    }

    public function setProperty(?string $Property): self
    {
        $this->Property = $Property;

        return $this;
    }
}

src/Form/PaymentType.php
<?php

namespace App\Form;

use Symfony\Component\Validator\Constraints as Assert;
use App\Entity\Payments;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class PaymentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Invoice', NumberType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'label' => 'Facture :',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\NotBlank(),
                ]
            ])

            ->add('Amount', NumberType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'label' => 'Montant :',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\NotBlank(),
                ]
            ])

            ->add('Tenant')

            ->add('Submit', SubmitType::class, [
                'attr' => [
                    "class" => 'btn btn-success mt-5',
                ],
                'label' => 'Ajouter le paiment',

            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Payments::class,
        ]);
    }
}

src/Controller/PaymentController.php
<?php

namespace App\Controller;

use App\Entity\Payments;
use App\Entity\Tenant;
use App\Form\PaymentType;
use App\Repository\PaymentsRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use PDO;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PaymentController extends AbstractController
{
    #[Route('/payment', name: 'app_payment', methods: ['GET'])]
    public function index(PaginatorInterface $paginator, PaymentsRepository $repository, Request $request): Response
    {
        $payments = $paginator->paginate(
            $repository->findAll(),
            $request->query->getInt('page', 1), /*page number*/
            10
        );

        return $this->render('payment/payment.html.twig', [
            'payments' => $payments
        ]);
    }

    #[Route('/payment/edit/{id}', 'app_payment_edit',  methods: ['GET', 'POST'])]
    public function edit(Payments $payment, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(PaymentType::class, $payment);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $payment = $form->getData();


            $manager->persist($payment);
            $manager->flush();

            $this->addFlash(
                'success',
                'Le paiment à été modifié avec succès !'
            );

            return $this->redirectToRoute('app_payment');
        }

        return $this->render('payment/editPayment.html.twig', [
            'form' => $form->createView()
        ]);
    }

    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/payment/bilancompte/{id}', 'app_payment_bilancompte',  methods: ['GET'])]
    public function show($id): Response

    {

        $tenant = $this->entityManager->getRepository(Tenant::class)->find($id);
        $payments = $this->entityManager->getRepository(Payments::class)->findBy(['Tenant' => $tenant]);



        return $this->render('payment/bilancompte.html.twig', [
            'payments' => $payments
        ]);
    }


    #[Route('/payment/delete/{id}', 'app_payment_delete',  methods: ['GET'])]
    public function delete(EntityManagerInterface $manager, Payments $payment): Response
    {
        $manager->remove($payment);
        $manager->flush();


        $this->addFlash(
            'success',
            'Le paiment à été supprimé avec succès !'
        );

        return $this->redirectToRoute('app_payment');
    }
}

templates/payment/bilancompte.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Editer un paiment
{% endblock %}

{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-success">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ path('app_home') }}">AgenceImmobillièreFictive</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor03">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_property') }}">Propriétées
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_tenant') }}">Locataires
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_payment') }}">Paiements
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_etat_des_lieux') }}">Etat des lieux
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_login_logout') }}">Se déconnecter
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<h1 class="mt-5">
			Récapitulatif des paiments
		</h1>


		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">Numéros</th>
					<th scope="col">Locataire</th>
					<th scope="col">Propriétée</th>
					<th scope="col">Facture</th>
					<th scope="col">Montant</th>
					<th scope="col">Date de l'opération</th>
					<th scope="col"></th>
					<th scope="col"></th>
				</tr>
			</thead>

			<tbody>
				{% for payment in payments|sort %}
					<tr class="table-light">
						<th scope="row">{{ payment.id }}</th>
						<td>{{ payment.tenant }}</td>
						<td>{{ payment.property }}</td>
						<td>{{ payment.invoice }}</td>
						<td>{{ payment.amount }}</td>
						<td>
							{{ payment.createdAt|date("d/m/Y") }}</td>
						<td>
							<a href="{{ path('app_payment_edit', {id: payment.id}) }}" class="btn btn-warning">
								Editer
							</a>
						</td>
						<td>
							<a href="{{ path('app_payment_bilancompte', {id: payment.id}) }}" class="btn btn-primary">
								Bilan
							</a>
						</td>
						<td>
							<a href="{{ path('app_payment_delete', {id: payment.id}) }}" class="btn btn-danger">
								Supprimer
							</a>
						</td>

					</tr>
				{% endfor %}
			</tbody>
		</table>


	{% endblock %}

templates/payment/editPayment.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Editer un paiment
{% endblock %}

{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-success">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ path('app_home') }}">AgenceImmobillièreFictive</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor03">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_property') }}">Propriétées
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_tenant') }}">Locataires
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_payment') }}">Paiements
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_etat_des_lieux') }}">Etat des lieux
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_login_logout') }}">Se déconnecter
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<h1 class="mt-5">
			Modifier un paiment
		</h1>

		{{ form_start(form) }}
		<div class="row">
			<div class="col-md-4">{{ form_row(form.Invoice)}}</div>
			<div class="col-md-4">{{ form_row(form.Amount)}}</div>
		</div>

		{{ form_end(form) }}
	</div>
	{{ form_end(form) }}
</div>{% endblock %}

templates/payment/newPayment.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Ajouter un paiment
{% endblock %}

{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-success">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ path('app_home') }}">AgenceImmobillièreFictive</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor03">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_property') }}">Propriétées
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_tenant') }}">Locataires
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_payment') }}">Paiements
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_etat_des_lieux') }}">Etat des lieux
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_login_logout') }}">Se déconnecter
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<h1 class="mt-5">
			Ajouter un paiment
		</h1>

		{{ form_start(form) }}
		<div class="row">
			<div class="col-md-4">{{ form_row(form.Invoice)}}</div>
			<div class="col-md-4">{{ form_row(form.Amount)}}</div>
		</div>

		{{ form_end(form) }}
	</div>

{% endblock %}

templates/payment/payment.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Paiments
{% endblock %}

{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-success">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ path('app_home') }}">AgenceImmobillièreFictive</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor03">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_property') }}">Propriétées
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_tenant') }}">Locataires
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_payment') }}">Paiements
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_etat_des_lieux') }}">Etat des lieux
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{{ path('app_login_logout') }}">Se déconnecter
							<span class="visually-hidden">(current)</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div style="padding: 75px;" class="mt-4">
		<div class="jumbotron">
			<h1 class="mb-5">
				Liste des paiements
			</h1>

			<table class="table table-hover">
				<thead>
					<tr>
						<th scope="col">Numéros</th>
						<th scope="col">Locataire</th>
						<th scope="col">Propriété</th>
						<th scope="col">Facture</th>
						<th scope="col">Montant</th>
						<th scope="col">Date de l'opération</th>
						<th scope="col"></th>
						<th scope="col"></th>
					</tr>
				</thead>

				<tbody>
					{% for payment in payments|sort %}
						<tr class="table-light">
							<th scope="row">{{ payment.id }}</th>
							<td>{{ payment.tenant }}</td>
							<td>{{ payment.property }}</td>
							<td>{{ payment.invoice }}</td>
							<td>{{ payment.amount }}</td>
							<td>
								{{ payment.createdAt|date("d/m/Y") }}</td>
							<td>
								<a href="{{ path('app_payment_edit', {id: payment.id}) }}" class="btn btn-warning">
									Editer
								</a>
							</td>
							<td>
								<a href="{{ path('app_payment_bilancompte', {id: payment.tenant.id}) }}" class="btn btn-primary">
									Bilan
								</a>
							</td>
							<td>
								<a href="{{ path('app_payment_delete', {id: payment.id}) }}" class="btn btn-danger">
									Supprimer
								</a>
							</td>

						</tr>
					{% endfor %}
				</tbody>
			</table>

			<div class="navigation d-flex justify-content-center">
				{{ knp_pagination_render(payments) }}
			</div>

			<a href="{{ path('app_property') }}" class="btn btn-success mt-4 d-flex justify-content-center">
				Ajouter un paiment
			</a>

		</div>
	</div>
{% endblock %}